select * from customer_data limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?  
select gender, SUM(purchase_amount) as revenue
from customer_data
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer_data
group by item_purchased
order by avg(review_rating) desc
limit 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        SUM(discount_applied = 'Yes') / COUNT(*) * 100,
        2
    ) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
WITH customer_segments AS (
SELECT customer_id,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
FROM customer_data
)
SELECT
    customer_segment,
    COUNT(*) AS total_customers
FROM customer_segments
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
SELECT category, item_purchased, COUNT(*) AS total_orders,
ROW_NUMBER() OVER (
                 PARTITION BY category ORDER BY COUNT(*) DESC
                   ) AS product_rank
FROM customer_data
GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    total_orders,
    product_rank
FROM item_counts
WHERE product_rank <= 3;

 
-- Q9. How does purchase frequency affect average spending?
SELECT
    frequency_of_purchases,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer_data
GROUP BY frequency_of_purchases
ORDER BY avg_purchase DESC;


-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue desc;


-- Q11. Which categories and seasons generate the highest revenue?
SELECT 
    season,
    category,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer_data
GROUP BY season, category
ORDER BY total_revenue DESC;


-- Q12. Does using a discount_applied actually increase customer spending?
SELECT 
    discount_applied,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_data
GROUP BY discount_applied
ORDER BY avg_purchase DESC;


-- Q13. Which payment methods are most popular, and how much revenue does each generate? 
SELECT 
    payment_method,
    COUNT(*) AS total_orders,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_data
GROUP BY payment_method
ORDER BY total_revenue DESC;

-- Q14. Which locations have the highest customer value?
SELECT 
    location,
    COUNT(*) AS total_customers,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_data
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;






















